/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package find;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

class FindTest {
    @Test
    void test1 () throws IOException {
        ArrayList<String> expected = new ArrayList<>();
        expected.add("input/gggg.txt");
        expected.add("input/fileName.txt");
        ArrayList<File> file;
        ArrayList<String> actual = new ArrayList<>();
        Find run = new Find(); //создаем объект класса Find, чтобы применить к нему нашу функцию
        file = run.DoMain("-d input gggg.txt fileName.txt".trim().split("\s+")); // результат
        for (int i = 0; i < file.size(); i++){
            actual.add(file.get(i).toString());
        } // преобразование в стринг результатов
        Assertions.assertEquals(expected, actual);
    }

    @Test
    void test2 () throws IOException {
        ArrayList<String> expected = new ArrayList<>();
        expected.add("input/fileName.txt");
        ArrayList<File> file;
        ArrayList<String> actual = new ArrayList<>();
        Find run = new Find();
        file = run.DoMain("-d input -r fileName.txt".trim().split("\s+"));
        for (int i = 0; i < file.size(); i++){
            actual.add(file.get(i).toString());
        }
        Assertions.assertEquals(expected, actual);
    }

    @Test
    void test3 () throws IOException {
        ArrayList<String> expected = new ArrayList<>();
        expected.add("input/fileName.txt");
        ArrayList<File> file;
        ArrayList<String> actual = new ArrayList<>();
        Find run = new Find();
        file = run.DoMain("-d input fileName.txt jfdj.txt".trim().split("\s+"));
        for (int i = 0; i < file.size(); i++){
            actual.add(file.get(i).toString());
        }
        Assertions.assertEquals(expected, actual);
    }

    @Test
    void test4 () throws IOException {
        ArrayList<String> expected = new ArrayList<>();
        ArrayList<File> file;
        ArrayList<String> actual = new ArrayList<>();
        Find run = new Find();
        file = run.DoMain("-d input -r ghfjd.txt".trim().split("\s+"));
        for (int i = 0; i < file.size(); i++){
            actual.add(file.get(i).toString());
        }
        Assertions.assertEquals(expected, actual);
    }

    @Test
    void test5 () throws IOException {
        ArrayList<String> expected = new ArrayList<>();
        ArrayList<File> file;
        ArrayList<String> actual = new ArrayList<>();
        Find run = new Find();
        file = run.DoMain("-d gradle gggg.txt".trim().split("\s+"));
        for (int i = 0; i < file.size(); i++){
            actual.add(file.get(i).toString());
        }
        Assertions.assertEquals(expected, actual);
    }
}

