/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.task2;

import org.junit.jupiter.api.Test;
import org.kohsuke.args4j.CmdLineException;
import org.kohsuke.args4j.CmdLineParser;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class DuTest {
    Du du = new Du();
    @Test void appHasAGreeting() {


    }

    //incorrect argument
    @Test
    public void app() throws CmdLineException {


    }
}
