/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.task2;

import org.junit.Test;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import static org.junit.Assert.*;

public class PackRLETests {

    @Test
    public void packerStringTest() {
        PackRLE packRLE = new PackRLE();
        String packString1 = packRLE.packer("BBBBBBBBBBBBIIIIIIIIIIIGGGG DUBBBB MMMMMAAAAAAAAAAAATTTTTTEEEEEEEEE");
        assertEquals("12B11I4G DU4B 5M12A6T9E", packString1);

        String packString2 = packRLE.packer("TTTTTTTTTTTHHHHHIIIIIIIISSSS ISSSS AAA TTTTEEESSSSTTTT");
        assertEquals("11T5H8I4S I4S 3A 4T3E4S4T", packString2);
    }

    @Test
    public void unpackerStringTest() {
        PackRLE packRLE = new PackRLE();
        String unpackString1 = packRLE.unpacker("11T5H8I4S I4S 3A 4T3E4S4T");
        assertEquals("TTTTTTTTTTTHHHHHIIIIIIIISSSS ISSSS AAA TTTTEEESSSSTTTT", unpackString1);

        String unpackString2 = packRLE.unpacker("12B11I4G DU4B 5M12A6T9E");
        assertEquals("BBBBBBBBBBBBIIIIIIIIIIIGGGG DUBBBB MMMMMAAAAAAAAAAAATTTTTTEEEEEEEEE", unpackString2);
    }


    private boolean contentEquals(String expectedName, String actualName) throws IOException {
        List<String> expectedLines = Files.readAllLines(Paths.get(expectedName));
        List<String> actualLines = Files.readAllLines(Paths.get(actualName));

        for (int i = 0; i < expectedLines.size(); i++) {
            if (!expectedLines.get(i).equals(actualLines.get(i))) return false;
        }
        return true;
    }

    @Test
    public void packerFileTest() throws IOException {
        String cmd = "-z -out src/main/resources/testRes/output1.txt src/main/resources/testRes/input1.txt";
        String expected = "src/main/resources/testRes/result1.txt";
        String actual = "src/main/resources/testRes/output1.txt";

        PackRLEParser.main(cmd.split(" "));

        assertTrue(contentEquals(expected, actual));
    }

    @Test
    public void unpackerFileTest() throws IOException {
        String cmd = "-u -out src/main/resources/testRes/output2.txt src/main/resources/testRes/input2.txt";
        String expected = "src/main/resources/testRes/result2.txt";
        String actual = "src/main/resources/testRes/output2.txt";

        PackRLEParser.main(cmd.split(" "));

        assertTrue(contentEquals(expected, actual));
    }

    @Test
    public void poemPack() throws IOException {
        String cmd = "-z -out src/main/resources/testRes/output3.txt src/main/resources/testRes/input3.txt";
        String expected = "src/main/resources/testRes/result3.txt";
        String actual = "src/main/resources/testRes/output3.txt";

        PackRLEParser.main(cmd.split(" "));

        assertTrue(contentEquals(expected, actual));
    }

    @Test
    public void poemUnpack() throws IOException {
        String cmd = "-u -out src/main/resources/testRes/output4.txt src/main/resources/testRes/input4.txt";
        String expected = "src/main/resources/testRes/result4.txt";
        String actual = "src/main/resources/testRes/output4.txt";

        PackRLEParser.main(cmd.split(" "));

        assertTrue(contentEquals(expected, actual));
    }
}
