/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.task2;


public class PackRLE {

    public String packer(String content) {
        if (content.isEmpty()) return "";
        StringBuilder packResult = new StringBuilder();

        char[] chars = content.toCharArray();
        int sequenceLength = 0;
        char currentChar = chars[0];

        for (char c : chars) {
            if (currentChar == c) sequenceLength += 1;
            else {
                if (sequenceLength > 1) packResult.append(sequenceLength);
                packResult.append(currentChar);
                currentChar = c;
                sequenceLength = 1;
            }
        }
        if (sequenceLength > 1) packResult.append(sequenceLength);
        packResult.append(currentChar);

        return packResult.toString();
    }

    public String unpacker(String content) {
        if (content.isEmpty()) return "";
        StringBuilder unpackResult = new StringBuilder();
        StringBuilder digitSequence = new StringBuilder();

        char[] chars = content.toCharArray();
        boolean digitFlag = false;
        for (char c : chars) {
            if (Character.isDigit(c)) {
                digitFlag = true;
                digitSequence.append(c);
            } else {
                if (digitFlag) {
                    unpackResult.append(new String(new char[Integer.parseInt(digitSequence.toString())]).replace('\0', c));
                    digitFlag = false;
                    digitSequence.setLength(0);
                } else unpackResult.append(c);
            }
        }
        return unpackResult.toString();
    }
}
